/* *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁*.

Licensed under the  GPL-3.0 License;
you may not use this file except in compliance with the License.

Whats bot - Ravindu Manoj
*/

const Asena = require('../events');
const {MessageType, MessageOptions, Mimetype} = require('@adiwajshing/baileys');
const axios = require('axios');
const Config = require('../config');
const {spawnSync} = require('child_process');
const fs = require('fs');

const NNVL = "logo to image all manu.. *𝚄𝚜𝚎 𝚝𝚑𝚎 𝚏𝚘𝚕𝚕𝚘𝚠𝚒𝚗𝚐 𝚌𝚘𝚖𝚖𝚊𝚗𝚍𝚜 𝚝𝚘 𝚐𝚎𝚝 𝚝𝚑𝚎 𝚆𝚘𝚛𝚍 𝙿𝚒𝚌𝚝𝚞𝚛𝚎 𝙲𝚘𝚗𝚟𝚎𝚛𝚝𝚎𝚛 𝚖𝚎𝚗𝚞*"

if (Config.WORKTYPE == 'private') {
     
        Asena.addCommand({pattern: 'logomaker', fromMe: true, desc: NNVL}, (async (message, match) => {
      await message.sendMessage('👑 **˩σɢσ мακɛя** 👑\n  \n*𝚄𝚜𝚎 𝚝𝚑𝚎 𝚏𝚘𝚕𝚕𝚘𝚠𝚒𝚗𝚐 𝚌𝚘𝚖𝚖𝚊𝚗𝚍𝚜 𝚝𝚘 𝚐𝚎𝚝 𝚝𝚑𝚎 𝚆𝚘𝚛𝚍 𝙿𝚒𝚌𝚝𝚞𝚛𝚎 𝙲𝚘𝚗𝚟𝚎𝚛𝚝𝚎𝚛 𝚖𝚎𝚗𝚞*\n\n\n\n💠 .logo1\n\n💠 .logo2\n\n💠 .logo3\n\n💠 .logo4\n\n💠 .logo5\n\n💠 .logo6\n\n💠 .logo7\n\n💠 .logo8\n\n\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Asena.addCommand({pattern: 'logo1', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.dota2*\n✨Desc: it makes metal dota2 logo\n💍 Example : *.dota2 Ravindu*\n\n❄️Usage: *.avo*\n✨Desc: it makes metal avo logo\n💍 Example : *.avo Ravindu*\n\n❄️Usage: *.1lol*\n✨Desc: it makes metal 1lol logo\n💍 Example : *.1lol Ravindu*\n\n❄️Usage: *.2lol*\n✨Desc: it makes metal 2lol logo\n💍 Example : *.2lol Ravindu*\n\n❄️Usage: *.3lol*\n✨Desc: it makes metal 3lol logo\n💍 Example : *.3lol Ravind*\n\n❄️Usage: *.stars*\n✨Desc: it makes metal stars logo\n💍 Example : *.stara Ravindu*\n\n❄️Usage: *.fur*\n✨Desc: it makes metal fur logo\n💍 Example : *.fur Ravindu*\n\n❄️Usage: *.gerbang*\n✨Desc: it makes metal gerbang logo\n💍 Example : *.gerbang Ravindu*\n\n❄️Usage: *.grad*\n✨Desc: it makes metal grad logo\n💍 Example : *.grad Ravindu*\n\n❄️Usage: *.1spark*\n✨Desc: it makes metal 1spark logo\n💍 Example : *.1spark Ravindu*\n\n❄️Usage: *.2spark*\n✨Desc: it makes metal 2spark logo\n💍 Example : *.2spark Ravindu*\n\n❄️Usage: *.3spark*\n✨Desc: it makes metal 3spark logo\n💍 Example : *.3spark Ravindu*\n\n❄️Usage: *.4spark*\n✨Desc: it makes metal 4spark logo\n💍 Example : *.4spark Ravindu*\n\n❄️Usage: *.5spark*\n✨Desc: it makes metal 5spark logo\n💍 Example : *.5spark Ravindu*\n\n❄️Usage: *.biscuit*\n✨Desc: it makes metal biscuit logo\n💍 Example : *.biscuit Ravindu*\n\n❄️Usage: *.fish*\n✨Desc: it makes metal fisha logo\n💍 Example : *.fish Ravindu*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow Ravindu*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny Ravindu*\n\n❄️Usage: *.fruit*\n✨Desc: it makes metal fruit logo\n💍 Example : *.fruit Ravindu*\n\n❄️Usage: *.bluemetal*\n✨Desc: it makes metal bluemetal logo\n💍 Example : *.bluemetal Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Asena.addCommand({pattern: 'logo2', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.1candi*\n✨Desc: it makes metal 1candi logo\n💍 Example : *.1candi Ravindu*\n\n❄️Usage: *.2carbon*\n✨Desc: it makes metal 2carbon logo\n💍 Example : *.2carbon Ravindu*\n\n❄️Usage: *.2metal*\n✨Desc: it makes metal 2metal logo\n💍 Example : *.2metal Ravindu*\n\n❄️Usage: *.1glitter*\n✨Desc: it makes metal 1glitter logo\n💍 Example : *.1glitter Ravindu*\n\n❄️Usage: *.2glitter*\n✨Desc: it makes metal 2glitter logo\n💍 Example : *.2glitter Ravind*\n\n❄️Usage: *.3glitter*\n✨Desc: it makes metal 3glitter logo\n💍 Example : *.3glitter Ravindu*\n\n❄️Usage: *.4glitter*\n✨Desc: it makes metal 4glitter logo\n💍 Example : *.4glitter Ravindu*\n\n❄️Usage: *.5glitter*\n✨Desc: it makes metal 5glitter logo\n💍 Example : *.5glitter Ravindu*\n\n❄️Usage: *.6glitter*\n✨Desc: it makes metal 6glitter logo\n💍 Example : *.6glitter Ravindu*\n\n❄️Usage: *.7glitter*\n✨Desc: it makes metal 7glitter logo\n💍 Example : *.7glitter Ravindu*\n\n❄️Usage: *.1jewelry*\n✨Desc: it makes metal 1jewelry logo\n💍 Example : *.1jewelry Ravindu*\n\n❄️Usage: *.2jewelry*\n✨Desc: it makes metal 2jewelry logo\n💍 Example : *.2jewelry Ravindu*\n\n❄️Usage: *.3jewelry*\n✨Desc: it makes metal 3jewelry logo\n💍 Example : *.3jewelry Ravindu*\n\n❄️Usage: *.4jewelry*\n✨Desc: it makes metal 4jewelry logo\n💍 Example : *.4jewelry Ravindu*\n\n❄️Usage: *.5jewelry*\n✨Desc: it makes metal 5jewelry logo\n💍 Example : *.5jewelry Ravindu*\n\n❄️Usage: *.6jewelry*\n✨Desc: it makes metal 6jewelry logo\n💍 Example : *.6jewelry Ravindu*\n\n❄️Usage: *.7jewelry*\n✨Desc: it makes metal 7jewelry logo\n💍 Example : *.7jewelry Ravindu*\n\n❄️Usage: *.8jewelry*\n✨Desc: it makes metal 8jewelry logo\n💍 Example : *.8jewelry Ravindu*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny Ravindu*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Asena.addCommand({pattern: 'logo3', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.3cake*\n✨Desc: it makes metal 3cake logo\n💍 Example : *.3cake Ravindu*\n\n❄️Usage: *.captain*\n✨Desc: it makes metal captain logo\n💍 Example : *.captain Ravindu*\n\n❄️Usage: *.bagel*\n✨Desc: it makes metal bagel logo\n💍 Example : *.bagel Ravindu*\n\n❄️Usage: *.1gem*\n✨Desc: it makes metal 1gem logo\n💍 Example : *.1gem Ravindu*\n\n❄️Usage: *.berry*\n✨Desc: it makes metal berry logo\n💍 Example : *.berry Ravindu*\n\n❄️Usage: *.2blood*\n✨Desc: it makes metal 2blood logo\n💍 Example : *.2blood Ravindu*\n\n❄️Usage: *.3blood*\n✨Desc: it makes metal 3blood logo\n💍 Example : *.3blood Ravindu*\n\n❄️Usage: *.1glass*\n✨Desc: it makes metal 1glass logo\n💍 Example : *.1glass Ravindu*\n\n❄️Usage: *.lava*\n✨Desc: it makes metal lava logo\n💍 Example : *.lava Ravindu*\n\n❄️Usage: *.rock*\n✨Desc: it makes metal rock logo\n💍 Example : *.rock Ravindu*\n\n❄️Usage: *.1decora*\n✨Desc: it makes metal 1decora logo\n💍 Example : *.1decora Ravindu*\n\n❄️Usage: *.2decora*\n✨Desc: it makes metal 2decora logo\n💍 Example : *.2decora Ravindu*\n\n❄️Usage: *.3decora*\n✨Desc: it makes metal 3decora logo\n💍 Example : *.3decora Ravindu*\n\n❄️Usage: *.1foil*\n✨Desc: it makes metal 1foil logo\n💍 Example : *.1foil Ravindu*\n\n❄️Usage: *.2foil*\n✨Desc: it makes metal 2foil logo\n💍 Example : *.2foil Ravindu*\n\n❄️Usage: *.3foil*\n✨Desc: it makes metal 3foil logo\n💍 Example : *.3foil Ravindu*\n\n❄️Usage: *.4foil*\n✨Desc: it makes metal 4foil logo\n💍 Example : *.4foil Ravindu*\n\n❄️Usage: *.5foil*\n✨Desc: it makes metal 5foil logo\n💍 Example : *.5foil Ravindu*\n\n❄️Usage: *.6foil*\n✨Desc: it makes metal 6foil logo\n💍 Example : *.6foil Ravindu*\n\n❄️Usage: *.7foil*\n✨Desc: it makes metal 7foil logo\n💍 Example : *.7foil Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Asena.addCommand({pattern: 'logo4', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.steel*\n✨Desc: it makes metal steel logo\n💍 Example : *.steel Ravindu*\n\n❄️Usage: *.1glossy*\n✨Desc: it makes metal 1glossy logo\n💍 Example : *.1glossy Ravindu*\n\n❄️Usage: *.2glossy*\n✨Desc: it makes metal 2glossy logo\n💍 Example : *.2glossy Ravindu*\n\n❄️Usage: *.denim*\n✨Desc: it makes metal denim logo\n💍 Example : *.denim Ravindu*\n\n❄️Usage: *.joker*\n✨Desc: it makes metal joker logo\n💍 Example : *.joker Ravindu*\n\n❄️Usage: *.wicker*\n✨Desc: it makes metal wicker logo\n💍 Example : *.wicker Ravindu*\n\n❄️Usage: *.skeleton*\n✨Desc: it makes metal skeleton logo\n💍 Example : *.skeleton Ravindu*\n\n❄️Usage: *.xmas3d*\n✨Desc: it makes metal xmas3d logo\n💍 Example : *.xmas3d Ravindu*\n\n❄️Usage: *.helloween*\n✨Desc: it makes metal helloween logo\n💍 Example : *.helloween Ravindu*\n\n❄️Usage: *.neon1s*\n✨Desc: it makes metal neon1s logo\n💍 Example : *.neon1s Ravindu*\n\n❄️Usage: *.new1y*\n✨Desc: it makes metal new1y logo\n💍 Example : *.new1y Ravindu*\n\n❄️Usage: *.1fabric*\n✨Desc: it makes metal 1fabric logo\n💍 Example : *.1fabric Ravindu*\n\n❄️Usage: *.purpule*\n✨Desc: it makes metal purpule logo\n💍 Example : *.purpule Ravindu*\n\n❄️Usage: *.holo3d*\n✨Desc: it makes metal holo3d logo\n💍 Example : *.holo3d Ravindu*\n\n❄️Usage: *.minion3d*\n✨Desc: it makes metal minion3d logo\n💍 Example : *.minion3d Ravindu*\n\n❄️Usage: *.neongalaxy*\n✨Desc: it makes metal neongalaxy logo\n💍 Example : *.neongalaxy Ravindu*\n\n❄️Usage: *.darkgold*\n✨Desc: it makes metal darkgold logo\n💍 Example : *.darkgold Ravindu*\n\n❄️Usage: *.1sandwriting*\n✨Desc: it makes metal 1sandwriting logo\n💍 Example : *.1sandwriting Ravindu*\n\n❄️Usage: *.cloudsky*\n✨Desc: it makes metal cloudsky logo\n💍 Example : *.cloudsky Ravindu*\n\n❄️Usage: *.3dluxury*\n✨Desc: it makes metal 3dluxury logo\n💍 Example : *.3dluxury Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Asena.addCommand({pattern: 'logo', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.sandsum*\n✨Desc: it makes metal sandsum logo\n💍 Example : *.sandsum Ravindu*\n\n❄️Usage: *.1917*\n✨Desc: it makes metal 1917 logo\n💍 Example : *.1917 Ravindu*\n\n❄️Usage: *.vlogo*\n✨Desc: it makes metal vlogo logo\n💍 Example : *.vlogo Ravindu*\n\n❄️Usage: *.plogo*\n✨Desc: it makes metal plogo logo\n💍 Example : *.plogo Ravindu*\n\n❄️Usage: *.colorlogo*\n✨Desc: it makes metal colorlogo logo\n💍 Example : *.colorlogo Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
}

else if (Config.WORKTYPE == 'public') {

     Asena.addCommand({pattern: 'sewmaker', fromMe: true, desc: Lang.NNVL}, (async (message, match) => {
      await message.sendMessage('👑 **˩σɢσ мακɛя** 👑\n  \n*𝚄𝚜𝚎 𝚝𝚑𝚎 𝚏𝚘𝚕𝚕𝚘𝚠𝚒𝚗𝚐 𝚌𝚘𝚖𝚖𝚊𝚗𝚍𝚜 𝚝𝚘 𝚐𝚎𝚝 𝚝𝚑𝚎 𝚆𝚘𝚛𝚍 𝙿𝚒𝚌𝚝𝚞𝚛𝚎 𝙲𝚘𝚗𝚟𝚎𝚛𝚝𝚎𝚛 𝚖𝚎𝚗𝚞*\n\n\n\n💠 .logo1\n\n💠 .logo2\n\n💠 .logo3\n\n💠 .logo4\n\n💠 .logo5\n\n💠 .logo6\n\n💠 .logo7\n\n💠 .logo8\n\n\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Asena.addCommand({pattern: 'logo1', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.dota2*\n✨Desc: it makes metal dota2 logo\n💍 Example : *.dota2 Ravindu*\n\n❄️Usage: *.avo*\n✨Desc: it makes metal avo logo\n💍 Example : *.avo Ravindu*\n\n❄️Usage: *.1lol*\n✨Desc: it makes metal 1lol logo\n💍 Example : *.1lol Ravindu*\n\n❄️Usage: *.2lol*\n✨Desc: it makes metal 2lol logo\n💍 Example : *.2lol Ravindu*\n\n❄️Usage: *.3lol*\n✨Desc: it makes metal 3lol logo\n💍 Example : *.3lol Ravind*\n\n❄️Usage: *.stars*\n✨Desc: it makes metal stars logo\n💍 Example : *.stara Ravindu*\n\n❄️Usage: *.fur*\n✨Desc: it makes metal fur logo\n💍 Example : *.fur Ravindu*\n\n❄️Usage: *.gerbang*\n✨Desc: it makes metal gerbang logo\n💍 Example : *.gerbang Ravindu*\n\n❄️Usage: *.grad*\n✨Desc: it makes metal grad logo\n💍 Example : *.grad Ravindu*\n\n❄️Usage: *.1spark*\n✨Desc: it makes metal 1spark logo\n💍 Example : *.1spark Ravindu*\n\n❄️Usage: *.2spark*\n✨Desc: it makes metal 2spark logo\n💍 Example : *.2spark Ravindu*\n\n❄️Usage: *.3spark*\n✨Desc: it makes metal 3spark logo\n💍 Example : *.3spark Ravindu*\n\n❄️Usage: *.4spark*\n✨Desc: it makes metal 4spark logo\n💍 Example : *.4spark Ravindu*\n\n❄️Usage: *.5spark*\n✨Desc: it makes metal 5spark logo\n💍 Example : *.5spark Ravindu*\n\n❄️Usage: *.biscuit*\n✨Desc: it makes metal biscuit logo\n💍 Example : *.biscuit Ravindu*\n\n❄️Usage: *.fish*\n✨Desc: it makes metal fisha logo\n💍 Example : *.fish Ravindu*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow Ravindu*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny Ravindu*\n\n❄️Usage: *.fruit*\n✨Desc: it makes metal fruit logo\n💍 Example : *.fruit Ravindu*\n\n❄️Usage: *.bluemetal*\n✨Desc: it makes metal bluemetal logo\n💍 Example : *.bluemetal Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Asena.addCommand({pattern: 'logo2', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.1candi*\n✨Desc: it makes metal 1candi logo\n💍 Example : *.1candi Ravindu*\n\n❄️Usage: *.2carbon*\n✨Desc: it makes metal 2carbon logo\n💍 Example : *.2carbon Ravindu*\n\n❄️Usage: *.2metal*\n✨Desc: it makes metal 2metal logo\n💍 Example : *.2metal Ravindu*\n\n❄️Usage: *.1glitter*\n✨Desc: it makes metal 1glitter logo\n💍 Example : *.1glitter Ravindu*\n\n❄️Usage: *.2glitter*\n✨Desc: it makes metal 2glitter logo\n💍 Example : *.2glitter Ravind*\n\n❄️Usage: *.3glitter*\n✨Desc: it makes metal 3glitter logo\n💍 Example : *.3glitter Ravindu*\n\n❄️Usage: *.4glitter*\n✨Desc: it makes metal 4glitter logo\n💍 Example : *.4glitter Ravindu*\n\n❄️Usage: *.5glitter*\n✨Desc: it makes metal 5glitter logo\n💍 Example : *.5glitter Ravindu*\n\n❄️Usage: *.6glitter*\n✨Desc: it makes metal 6glitter logo\n💍 Example : *.6glitter Ravindu*\n\n❄️Usage: *.7glitter*\n✨Desc: it makes metal 7glitter logo\n💍 Example : *.7glitter Ravindu*\n\n❄️Usage: *.1jewelry*\n✨Desc: it makes metal 1jewelry logo\n💍 Example : *.1jewelry Ravindu*\n\n❄️Usage: *.2jewelry*\n✨Desc: it makes metal 2jewelry logo\n💍 Example : *.2jewelry Ravindu*\n\n❄️Usage: *.3jewelry*\n✨Desc: it makes metal 3jewelry logo\n💍 Example : *.3jewelry Ravindu*\n\n❄️Usage: *.4jewelry*\n✨Desc: it makes metal 4jewelry logo\n💍 Example : *.4jewelry Ravindu*\n\n❄️Usage: *.5jewelry*\n✨Desc: it makes metal 5jewelry logo\n💍 Example : *.5jewelry Ravindu*\n\n❄️Usage: *.6jewelry*\n✨Desc: it makes metal 6jewelry logo\n💍 Example : *.6jewelry Ravindu*\n\n❄️Usage: *.7jewelry*\n✨Desc: it makes metal 7jewelry logo\n💍 Example : *.7jewelry Ravindu*\n\n❄️Usage: *.8jewelry*\n✨Desc: it makes metal 8jewelry logo\n💍 Example : *.8jewelry Ravindu*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny Ravindu*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Asena.addCommand({pattern: 'logo3', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.3cake*\n✨Desc: it makes metal 3cake logo\n💍 Example : *.3cake Ravindu*\n\n❄️Usage: *.captain*\n✨Desc: it makes metal captain logo\n💍 Example : *.captain Ravindu*\n\n❄️Usage: *.bagel*\n✨Desc: it makes metal bagel logo\n💍 Example : *.bagel Ravindu*\n\n❄️Usage: *.1gem*\n✨Desc: it makes metal 1gem logo\n💍 Example : *.1gem Ravindu*\n\n❄️Usage: *.berry*\n✨Desc: it makes metal berry logo\n💍 Example : *.berry Ravindu*\n\n❄️Usage: *.2blood*\n✨Desc: it makes metal 2blood logo\n💍 Example : *.2blood Ravindu*\n\n❄️Usage: *.3blood*\n✨Desc: it makes metal 3blood logo\n💍 Example : *.3blood Ravindu*\n\n❄️Usage: *.1glass*\n✨Desc: it makes metal 1glass logo\n💍 Example : *.1glass Ravindu*\n\n❄️Usage: *.lava*\n✨Desc: it makes metal lava logo\n💍 Example : *.lava Ravindu*\n\n❄️Usage: *.rock*\n✨Desc: it makes metal rock logo\n💍 Example : *.rock Ravindu*\n\n❄️Usage: *.1decora*\n✨Desc: it makes metal 1decora logo\n💍 Example : *.1decora Ravindu*\n\n❄️Usage: *.2decora*\n✨Desc: it makes metal 2decora logo\n💍 Example : *.2decora Ravindu*\n\n❄️Usage: *.3decora*\n✨Desc: it makes metal 3decora logo\n💍 Example : *.3decora Ravindu*\n\n❄️Usage: *.1foil*\n✨Desc: it makes metal 1foil logo\n💍 Example : *.1foil Ravindu*\n\n❄️Usage: *.2foil*\n✨Desc: it makes metal 2foil logo\n💍 Example : *.2foil Ravindu*\n\n❄️Usage: *.3foil*\n✨Desc: it makes metal 3foil logo\n💍 Example : *.3foil Ravindu*\n\n❄️Usage: *.4foil*\n✨Desc: it makes metal 4foil logo\n💍 Example : *.4foil Ravindu*\n\n❄️Usage: *.5foil*\n✨Desc: it makes metal 5foil logo\n💍 Example : *.5foil Ravindu*\n\n❄️Usage: *.6foil*\n✨Desc: it makes metal 6foil logo\n💍 Example : *.6foil Ravindu*\n\n❄️Usage: *.7foil*\n✨Desc: it makes metal 7foil logo\n💍 Example : *.7foil Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Asena.addCommand({pattern: 'logo4', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.steel*\n✨Desc: it makes metal steel logo\n💍 Example : *.steel Ravindu*\n\n❄️Usage: *.1glossy*\n✨Desc: it makes metal 1glossy logo\n💍 Example : *.1glossy Ravindu*\n\n❄️Usage: *.2glossy*\n✨Desc: it makes metal 2glossy logo\n💍 Example : *.2glossy Ravindu*\n\n❄️Usage: *.denim*\n✨Desc: it makes metal denim logo\n💍 Example : *.denim Ravindu*\n\n❄️Usage: *.joker*\n✨Desc: it makes metal joker logo\n💍 Example : *.joker Ravindu*\n\n❄️Usage: *.wicker*\n✨Desc: it makes metal wicker logo\n💍 Example : *.wicker Ravindu*\n\n❄️Usage: *.skeleton*\n✨Desc: it makes metal skeleton logo\n💍 Example : *.skeleton Ravindu*\n\n❄️Usage: *.xmas3d*\n✨Desc: it makes metal xmas3d logo\n💍 Example : *.xmas3d Ravindu*\n\n❄️Usage: *.helloween*\n✨Desc: it makes metal helloween logo\n💍 Example : *.helloween Ravindu*\n\n❄️Usage: *.neon1s*\n✨Desc: it makes metal neon1s logo\n💍 Example : *.neon1s Ravindu*\n\n❄️Usage: *.new1y*\n✨Desc: it makes metal new1y logo\n💍 Example : *.new1y Ravindu*\n\n❄️Usage: *.1fabric*\n✨Desc: it makes metal 1fabric logo\n💍 Example : *.1fabric Ravindu*\n\n❄️Usage: *.purpule*\n✨Desc: it makes metal purpule logo\n💍 Example : *.purpule Ravindu*\n\n❄️Usage: *.holo3d*\n✨Desc: it makes metal holo3d logo\n💍 Example : *.holo3d Ravindu*\n\n❄️Usage: *.minion3d*\n✨Desc: it makes metal minion3d logo\n💍 Example : *.minion3d Ravindu*\n\n❄️Usage: *.neongalaxy*\n✨Desc: it makes metal neongalaxy logo\n💍 Example : *.neongalaxy Ravindu*\n\n❄️Usage: *.darkgold*\n✨Desc: it makes metal darkgold logo\n💍 Example : *.darkgold Ravindu*\n\n❄️Usage: *.1sandwriting*\n✨Desc: it makes metal 1sandwriting logo\n💍 Example : *.1sandwriting Ravindu*\n\n❄️Usage: *.cloudsky*\n✨Desc: it makes metal cloudsky logo\n💍 Example : *.cloudsky Ravindu*\n\n❄️Usage: *.3dluxury*\n✨Desc: it makes metal 3dluxury logo\n💍 Example : *.3dluxury Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Asena.addCommand({pattern: 'logo', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.sandsum*\n✨Desc: it makes metal sandsum logo\n💍 Example : *.sandsum Ravindu*\n\n❄️Usage: *.1917*\n✨Desc: it makes metal 1917 logo\n💍 Example : *.1917 Ravindu*\n\n❄️Usage: *.vlogo*\n✨Desc: it makes metal vlogo logo\n💍 Example : *.vlogo Ravindu*\n\n❄️Usage: *.plogo*\n✨Desc: it makes metal plogo logo\n💍 Example : *.plogo Ravindu*\n\n❄️Usage: *.colorlogo*\n✨Desc: it makes metal colorlogo logo\n💍 Example : *.colorlogo Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Asena.addCommand({pattern: 'sewmaker', fromMe: false, desc: Lang.NNVL}, (async (message, match) => {
      await message.sendMessage('👑 **˩σɢσ мακɛя** 👑\n  \n*𝚄𝚜𝚎 𝚝𝚑𝚎 𝚏𝚘𝚕𝚕𝚘𝚠𝚒𝚗𝚐 𝚌𝚘𝚖𝚖𝚊𝚗𝚍𝚜 𝚝𝚘 𝚐𝚎𝚝 𝚝𝚑𝚎 𝚆𝚘𝚛𝚍 𝙿𝚒𝚌𝚝𝚞𝚛𝚎 𝙲𝚘𝚗𝚟𝚎𝚛𝚝𝚎𝚛 𝚖𝚎𝚗𝚞*\n\n\n\n💠 .logo1\n\n💠 .logo2\n\n💠 .logo3\n\n💠 .logo4\n\n💠 .logo5\n\n💠 .logo6\n\n💠 .logo7\n\n💠 .logo8\n\n\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Asena.addCommand({pattern: 'logo1', fromMe: false, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.dota2*\n✨Desc: it makes metal dota2 logo\n💍 Example : *.dota2 Ravindu*\n\n❄️Usage: *.avo*\n✨Desc: it makes metal avo logo\n💍 Example : *.avo Ravindu*\n\n❄️Usage: *.1lol*\n✨Desc: it makes metal 1lol logo\n💍 Example : *.1lol Ravindu*\n\n❄️Usage: *.2lol*\n✨Desc: it makes metal 2lol logo\n💍 Example : *.2lol Ravindu*\n\n❄️Usage: *.3lol*\n✨Desc: it makes metal 3lol logo\n💍 Example : *.3lol Ravind*\n\n❄️Usage: *.stars*\n✨Desc: it makes metal stars logo\n💍 Example : *.stara Ravindu*\n\n❄️Usage: *.fur*\n✨Desc: it makes metal fur logo\n💍 Example : *.fur Ravindu*\n\n❄️Usage: *.gerbang*\n✨Desc: it makes metal gerbang logo\n💍 Example : *.gerbang Ravindu*\n\n❄️Usage: *.grad*\n✨Desc: it makes metal grad logo\n💍 Example : *.grad Ravindu*\n\n❄️Usage: *.1spark*\n✨Desc: it makes metal 1spark logo\n💍 Example : *.1spark Ravindu*\n\n❄️Usage: *.2spark*\n✨Desc: it makes metal 2spark logo\n💍 Example : *.2spark Ravindu*\n\n❄️Usage: *.3spark*\n✨Desc: it makes metal 3spark logo\n💍 Example : *.3spark Ravindu*\n\n❄️Usage: *.4spark*\n✨Desc: it makes metal 4spark logo\n💍 Example : *.4spark Ravindu*\n\n❄️Usage: *.5spark*\n✨Desc: it makes metal 5spark logo\n💍 Example : *.5spark Ravindu*\n\n❄️Usage: *.biscuit*\n✨Desc: it makes metal biscuit logo\n💍 Example : *.biscuit Ravindu*\n\n❄️Usage: *.fish*\n✨Desc: it makes metal fisha logo\n💍 Example : *.fish Ravindu*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow Ravindu*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny Ravindu*\n\n❄️Usage: *.fruit*\n✨Desc: it makes metal fruit logo\n💍 Example : *.fruit Ravindu*\n\n❄️Usage: *.bluemetal*\n✨Desc: it makes metal bluemetal logo\n💍 Example : *.bluemetal Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Asena.addCommand({pattern: 'logo2', fromMe: false, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.1candi*\n✨Desc: it makes metal 1candi logo\n💍 Example : *.1candi Ravindu*\n\n❄️Usage: *.2carbon*\n✨Desc: it makes metal 2carbon logo\n💍 Example : *.2carbon Ravindu*\n\n❄️Usage: *.2metal*\n✨Desc: it makes metal 2metal logo\n💍 Example : *.2metal Ravindu*\n\n❄️Usage: *.1glitter*\n✨Desc: it makes metal 1glitter logo\n💍 Example : *.1glitter Ravindu*\n\n❄️Usage: *.2glitter*\n✨Desc: it makes metal 2glitter logo\n💍 Example : *.2glitter Ravind*\n\n❄️Usage: *.3glitter*\n✨Desc: it makes metal 3glitter logo\n💍 Example : *.3glitter Ravindu*\n\n❄️Usage: *.4glitter*\n✨Desc: it makes metal 4glitter logo\n💍 Example : *.4glitter Ravindu*\n\n❄️Usage: *.5glitter*\n✨Desc: it makes metal 5glitter logo\n💍 Example : *.5glitter Ravindu*\n\n❄️Usage: *.6glitter*\n✨Desc: it makes metal 6glitter logo\n💍 Example : *.6glitter Ravindu*\n\n❄️Usage: *.7glitter*\n✨Desc: it makes metal 7glitter logo\n💍 Example : *.7glitter Ravindu*\n\n❄️Usage: *.1jewelry*\n✨Desc: it makes metal 1jewelry logo\n💍 Example : *.1jewelry Ravindu*\n\n❄️Usage: *.2jewelry*\n✨Desc: it makes metal 2jewelry logo\n💍 Example : *.2jewelry Ravindu*\n\n❄️Usage: *.3jewelry*\n✨Desc: it makes metal 3jewelry logo\n💍 Example : *.3jewelry Ravindu*\n\n❄️Usage: *.4jewelry*\n✨Desc: it makes metal 4jewelry logo\n💍 Example : *.4jewelry Ravindu*\n\n❄️Usage: *.5jewelry*\n✨Desc: it makes metal 5jewelry logo\n💍 Example : *.5jewelry Ravindu*\n\n❄️Usage: *.6jewelry*\n✨Desc: it makes metal 6jewelry logo\n💍 Example : *.6jewelry Ravindu*\n\n❄️Usage: *.7jewelry*\n✨Desc: it makes metal 7jewelry logo\n💍 Example : *.7jewelry Ravindu*\n\n❄️Usage: *.8jewelry*\n✨Desc: it makes metal 8jewelry logo\n💍 Example : *.8jewelry Ravindu*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny Ravindu*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Asena.addCommand({pattern: 'logo3', fromMe: false, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.3cake*\n✨Desc: it makes metal 3cake logo\n💍 Example : *.3cake Ravindu*\n\n❄️Usage: *.captain*\n✨Desc: it makes metal captain logo\n💍 Example : *.captain Ravindu*\n\n❄️Usage: *.bagel*\n✨Desc: it makes metal bagel logo\n💍 Example : *.bagel Ravindu*\n\n❄️Usage: *.1gem*\n✨Desc: it makes metal 1gem logo\n💍 Example : *.1gem Ravindu*\n\n❄️Usage: *.berry*\n✨Desc: it makes metal berry logo\n💍 Example : *.berry Ravindu*\n\n❄️Usage: *.2blood*\n✨Desc: it makes metal 2blood logo\n💍 Example : *.2blood Ravindu*\n\n❄️Usage: *.3blood*\n✨Desc: it makes metal 3blood logo\n💍 Example : *.3blood Ravindu*\n\n❄️Usage: *.1glass*\n✨Desc: it makes metal 1glass logo\n💍 Example : *.1glass Ravindu*\n\n❄️Usage: *.lava*\n✨Desc: it makes metal lava logo\n💍 Example : *.lava Ravindu*\n\n❄️Usage: *.rock*\n✨Desc: it makes metal rock logo\n💍 Example : *.rock Ravindu*\n\n❄️Usage: *.1decora*\n✨Desc: it makes metal 1decora logo\n💍 Example : *.1decora Ravindu*\n\n❄️Usage: *.2decora*\n✨Desc: it makes metal 2decora logo\n💍 Example : *.2decora Ravindu*\n\n❄️Usage: *.3decora*\n✨Desc: it makes metal 3decora logo\n💍 Example : *.3decora Ravindu*\n\n❄️Usage: *.1foil*\n✨Desc: it makes metal 1foil logo\n💍 Example : *.1foil Ravindu*\n\n❄️Usage: *.2foil*\n✨Desc: it makes metal 2foil logo\n💍 Example : *.2foil Ravindu*\n\n❄️Usage: *.3foil*\n✨Desc: it makes metal 3foil logo\n💍 Example : *.3foil Ravindu*\n\n❄️Usage: *.4foil*\n✨Desc: it makes metal 4foil logo\n💍 Example : *.4foil Ravindu*\n\n❄️Usage: *.5foil*\n✨Desc: it makes metal 5foil logo\n💍 Example : *.5foil Ravindu*\n\n❄️Usage: *.6foil*\n✨Desc: it makes metal 6foil logo\n💍 Example : *.6foil Ravindu*\n\n❄️Usage: *.7foil*\n✨Desc: it makes metal 7foil logo\n💍 Example : *.7foil Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Asena.addCommand({pattern: 'logo4', fromMe: false, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.steel*\n✨Desc: it makes metal steel logo\n💍 Example : *.steel Ravindu*\n\n❄️Usage: *.1glossy*\n✨Desc: it makes metal 1glossy logo\n💍 Example : *.1glossy Ravindu*\n\n❄️Usage: *.2glossy*\n✨Desc: it makes metal 2glossy logo\n💍 Example : *.2glossy Ravindu*\n\n❄️Usage: *.denim*\n✨Desc: it makes metal denim logo\n💍 Example : *.denim Ravindu*\n\n❄️Usage: *.joker*\n✨Desc: it makes metal joker logo\n💍 Example : *.joker Ravindu*\n\n❄️Usage: *.wicker*\n✨Desc: it makes metal wicker logo\n💍 Example : *.wicker Ravindu*\n\n❄️Usage: *.skeleton*\n✨Desc: it makes metal skeleton logo\n💍 Example : *.skeleton Ravindu*\n\n❄️Usage: *.xmas3d*\n✨Desc: it makes metal xmas3d logo\n💍 Example : *.xmas3d Ravindu*\n\n❄️Usage: *.helloween*\n✨Desc: it makes metal helloween logo\n💍 Example : *.helloween Ravindu*\n\n❄️Usage: *.neon1s*\n✨Desc: it makes metal neon1s logo\n💍 Example : *.neon1s Ravindu*\n\n❄️Usage: *.new1y*\n✨Desc: it makes metal new1y logo\n💍 Example : *.new1y Ravindu*\n\n❄️Usage: *.1fabric*\n✨Desc: it makes metal 1fabric logo\n💍 Example : *.1fabric Ravindu*\n\n❄️Usage: *.purpule*\n✨Desc: it makes metal purpule logo\n💍 Example : *.purpule Ravindu*\n\n❄️Usage: *.holo3d*\n✨Desc: it makes metal holo3d logo\n💍 Example : *.holo3d Ravindu*\n\n❄️Usage: *.minion3d*\n✨Desc: it makes metal minion3d logo\n💍 Example : *.minion3d Ravindu*\n\n❄️Usage: *.neongalaxy*\n✨Desc: it makes metal neongalaxy logo\n💍 Example : *.neongalaxy Ravindu*\n\n❄️Usage: *.darkgold*\n✨Desc: it makes metal darkgold logo\n💍 Example : *.darkgold Ravindu*\n\n❄️Usage: *.1sandwriting*\n✨Desc: it makes metal 1sandwriting logo\n💍 Example : *.1sandwriting Ravindu*\n\n❄️Usage: *.cloudsky*\n✨Desc: it makes metal cloudsky logo\n💍 Example : *.cloudsky Ravindu*\n\n❄️Usage: *.3dluxury*\n✨Desc: it makes metal 3dluxury logo\n💍 Example : *.3dluxury Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Asena.addCommand({pattern: 'logo', fromMe: false, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.sandsum*\n✨Desc: it makes metal sandsum logo\n💍 Example : *.sandsum Ravindu*\n\n❄️Usage: *.1917*\n✨Desc: it makes metal 1917 logo\n💍 Example : *.1917 Ravindu*\n\n❄️Usage: *.vlogo*\n✨Desc: it makes metal vlogo logo\n💍 Example : *.vlogo Ravindu*\n\n❄️Usage: *.plogo*\n✨Desc: it makes metal plogo logo\n💍 Example : *.plogo Ravindu*\n\n❄️Usage: *.colorlogo*\n✨Desc: it makes metal colorlogo logo\n💍 Example : *.colorlogo Ravindu*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝙸𝙽𝚂𝙰𝙽𝙴-𝙱𝙾𝚈*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));

}
